apiVersion: v1
kind: Service
metadata:
  name: llama
  namespace: default
  labels:
    app: llama
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: llama
